import express from 'express';
import dotenv from 'dotenv';
import cors from 'cors';
import authRoutes from './routes/auth.js';
import txnRoutes from './routes/transactions.js';
import analyticsRoutes from './routes/analytics.js';
import usersRoutes from './routes/users.js';
import redis from './cache.js';
dotenv.config();
const app = express();
app.use(cors({ origin: process.env.CLIENT_URL || '*' }));
app.use(express.json());
app.use('/api/auth', authRoutes);
app.use('/api/transactions', txnRoutes);
app.use('/api/analytics', analyticsRoutes);
app.use('/api/users', usersRoutes);
app.get('/health', (req,res)=>res.json({ok:true}));
const port = process.env.PORT || 4000;
app.listen(port, ()=>console.log('listening',port));
process.on('SIGINT', ()=>{ redis.disconnect(); process.exit(); });
